from djitellopy import Tello

# ---
# Useful Tello Commands
# end()
# get_acceleration_x()
# get_acceleration_y()
# get_acceleration_z()
# get_battery()
# get_distance_tof()
# get_height()
# get_yaw()
# get_pitch()
# get_roll()
# get_speed_x()
# get_speed_y()
# get_speed_z()
# go_xyz_speed(x, y, z, speed)
# land()
# move(direction, x)
# move_back(x)
# move_down(x)
# move_forward(x)
# move_left(x)
# move_right(x)
# move_up(x)
# query_serial_number()
# reboot()
# rotate_clockwise(x)
# rotate_counter_clockwise(x)
# send_keepalive()
# send_rc_control(left_right_velocity, forward_backward_velocity, up_down_velocity, yaw_velocity)
# takeoff()
# ---

tello = Tello()
tello.connect()
tello.takeoff()
tello.rotate_counter_clockwise(90)
tello.rotate_clockwise(90)
tello.land()
